### ISSUE TITLE
HighPrivacy and Matomo

### ISSUE THREAD

**Issue by daganM** [AmauriC/tarteaucitron.js#290]
I'd like to disable auto-consent on scoll but still enable Matomo without consent,
is there a way to achieve that ?

**Comment by daganM** [comment]
@AmauriC Je me permets de relancer

**Comment by nicozerr** [comment]
Hello, Bonjour,

I have the same problem.

I have a website with several services: Youtube, Vimeo, and Matomo.
CNIL allows to enable Matomo without consent, but visitors must have possibility to disable Matomo (https://www.cnil.fr/fr/solutions-pour-les-cookies-de-mesure-daudience).
Matomo has needConsent=false but it's ignored if HighPrivacy=true. Disabling HighPrivacy is very bad idea as it will auto-consent all services on browsing.

In order to fix it, I replaced following line in tarteaucitron.js:
`isAllowed = (cookie.indexOf(service.key + '=true') >= 0) ? true : false`
by
`isAllowed = ((cookie.indexOf(service.key + '=true') >= 0) || (!service.needConsent)) ? true : false`

@AmauriC Is there a reason not to implement this fix ?
