### ISSUE TITLE
Not working with Matomo

### ISSUE THREAD

**Issue by sfaessler** [AmauriC/tarteaucitron.js#427]
Hi,

I have set everything up according to the instructions, but it does not work and in the Matomo backend it tells me that the code is not properly embedded. The popup works, also the small alert window on the bottom right works.
On the dashoard in Matomo it shows me no visitors since the beginning, although we have tested several calls within the circle of friends.

Does anyone have an idea?

The URL it is about is www.monkeybox.de

Thanks in advance for any help!

Regards,
Sven

**Comment by sfaessler** [comment]
After a while of debugging I've found out, that it seems that tarteaucitron.services.js is not loaded. I've added an alert() on top, which is not shown. Tested on latest Firefox and Google Chrome.

**Comment by Manoz** [comment]
Looks like you've found a solution :) I guess you can close this @AmauriC

**Comment by pierr0t** [comment]
Hello,
I'm kind of re-opening this (it's old but was never closed), because I ran into the same problem. Thks to @sfaessler for the solution. 
I think the real problem is with the installation guide which does not mention at all that "tarteaucitron.services.js" must be loaded with a separate "script" call. It seems obvious once you know it but I didn't think about this at all because I followed the guide step by step and it is not mentioned .... 
Pierre
