### ISSUE TITLE
Blocage du script suite à activation de règles CSP

### ISSUE THREAD

**Issue by LucasRachou** [AmauriC/tarteaucitron.js#463]
Bonjour, j'aimerais utiliser votre projet au sein de l'entreprise dans laquelle je travaille. 
Notre problème : nous avons des restrictions CSP (Content Security Policy) assez strictes qui empêchent l'utilisation du innerHTML et qui entrainent l'erreur suivante : "Refused to apply inline style because it violates the following Content Security Policy directive" (malgré que les sources du projet soient déclarées en local). 
Notre politique de sécurité nous interdit d'utiliser l'attribut 'unsafe-inline' qui pourrait solutionner le problème. 

Pouvez-vous envisager d'utiliser une autre propriété que hinnerHTML pour insérer du code dans la page sachant que l'utilisation des CSP est en train de se populariser ?

Merci pour votre aide.

**Comment by AmauriC** [comment]
Bonjour,

Actuellement non, le script n’est pas pensé pour se passer du innerHTML mais je note pour une future évolution ;)

**Comment by ldesgrange** [comment]
The PR #477 solves most of it (all the `onclick`), I still have some issues with 2 inlined styles:
- [Line 359](https://github.com/AmauriC/tarteaucitron.js/blob/067231da57c15a63098bccaa8ba1cbdea0593098/tarteaucitron.js#L359) is easily fixed by putting this style in tarteaucitron.css
- I'm not sure how to fix [lines 265 to 276](https://github.com/AmauriC/tarteaucitron.js/blob/067231da57c15a63098bccaa8ba1cbdea0593098/tarteaucitron.js#L265) without using something like a nonce.

**Comment by sir-gawain** [comment]
I updated the PR to the current master and also moved the css from line 359 to the external file.
I found some more inline styles in the code and moved them too.
I'm not sure, whats the purpose of this handling of css in lines 265-276, for me it looks as if a simple addClass() on an upper element and putting the css into the external file would do the trick much more elegant.
