### ISSUE TITLE
Bad release tags

### ISSUE THREAD

**Issue by davidlemaitre** [AmauriC/tarteaucitron.js#637]
It's difficult to follow releases of tarteaucitron in the Github repository. Last tags are comments like "Enable .min for jsdelivr" or dates like 20210305, not version numbers. 

The last versions of the npm package are 1.9.0 and 1.8.5. I'm unable to find the corresponding tags in the release page.

**Comment by AmauriC** [comment]
I know it's a terrible naming.

I made this because of a first bad naming '20200910' that was displayed as the latest tag on https://www.jsdelivr.com/package/gh/AmauriC/tarteaucitron.js

Every new version named like npm '1.9.0' looks older for jsdelivr and this is problem : /

With a naming like 20210305 it fix the problem on jsdelivr.

**Comment by JulioJu** [comment]
@AmauriC we could use https://www.jsdelivr.com/package/npm/tarteaucitronjs instead of https://www.jsdelivr.com/package/gh/AmauriC/tarteaucitron.js to follow GitHub and NPM release tags ?

Maybe the Wiki and the official doc on your website could be updated accordingly ?
